name: "super-productive-services"

services:
  db:
    image: postgres
    restart: always
    container_name: super-productive-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=super-productive
    volumes:
      - database-data:/var/lib/postgresql/data
    ports:
      - "8010:5432"

volumes:
  database-data:
